# Generated by Django 4.2.4 on 2023-09-03 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='Documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='Image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userfiles',
            name='Unknown',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=[], null=True, size=None),
        ),
    ]
