# Generated by Django 4.2.5 on 2023-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0002_uploadeduserfiles_delete_userfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeduserfiles',
            name='file_id',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
