# Generated by Django 4.2.5 on 2023-09-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utils', '0003_uploadeduserfiles_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeduserfiles',
            name='dbx',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
